name: Deploy JupyterLite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install jupyterlite-core jupyterlite-pyodide-kernel
      - run: jupyter lite build --contents jupyter --output-dir _output
      - uses: actions/upload-pages-artifact@v2
        with:
          path: _output

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2